replicaCount: 1
  
image:
  repository: hello-world
  tag: 1
  pullPolicy: IfNotPresent

service:
  type: NodePort
  targetPort: 8080
  port: 8080

resources:
  limits:
    cpu: 300m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi

#Environment Variables
env:
  NODE_ENV: development
  APP_HOST: localhost
  APP_PORT: 
  DB_USER: 
  DB_PASS: 
  DB_DATABASE: 
  DB_PORT: 
  DB_HOST: